language: python
matrix:
  include:
    - python: 3.7.4
      dist: xenial
      sudo: true
      env:
        - DJANGO=2.2.5
        - DEVELOPMENT=true
        - HOSTNAME='0.0.0.0'
        - IP='0.0.0.0'
        - PORT='5000'
        - MYTHMAKER_SECRET_KEY='whatever'
        - STRIPE_PUBLISHABLE_KEY='pk_test_WSMHaOkBZMUYsHyaNDDEsLGD00wJHHzet3'
install:
  - pip install -r requirements.txt
script: 
- python3 manage.py test || python manage.py test