language: python
python:
- "3.7.4"
services:
  - postgresql
env:
  - DJANGO=2.2.5
install:
  - pip install -r requirements.txt
script: 
- SECRET_KEY=os.environ.get("MYTHMAKER_SECRET_KEY") python manage.py test