# Generated by Django 2.2.5 on 2019-09-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20190924_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
