# Generated by Django 2.2.5 on 2019-11-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20191105_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio_likes',
            field=models.IntegerField(default=0),
        ),
    ]
