# Generated by Django 2.2.5 on 2019-11-12 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_audio_audio_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='audio', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'aiff', 'mp3'])]),
        ),
    ]
