# Generated by Django 2.2.5 on 2019-10-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
    ]
