# Generated by Django 2.2.5 on 2019-10-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20191028_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_thumbnail',
            field=models.ImageField(blank=True, upload_to='story_thumbnails'),
        ),
    ]
