# Generated by Django 2.2.5 on 2019-10-29 18:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_story_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True),
        ),
    ]
