# Generated by Django 2.2.5 on 2019-11-12 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_story_story_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_thumbnail',
            field=models.ImageField(blank=True, upload_to='story_thumbnails', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif', 'tiff'])]),
        ),
    ]
