# Generated by Django 2.2.5 on 2019-09-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mythmaker',
            name='tagline',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
