# Generated by Django 2.2.5 on 2019-09-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190926_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mythmaker',
            options={'verbose_name': 'MythMaker', 'verbose_name_plural': 'MythMakers'},
        ),
    ]
