# Generated by Django 2.2.5 on 2019-10-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190926_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Free', 'free'), ('Premium', 'prem')], default='Free', max_length=7),
        ),
    ]
