# Generated by Django 2.2.5 on 2019-10-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191009_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('FR', 'Free'), ('PR', 'Premium')], default='FR', max_length=2),
        ),
    ]
