# Generated by Django 2.2.5 on 2019-10-13 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191013_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('FR', 'Free'), ('PR', 'Premium')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mythmakermembership',
            name='membership',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Membership'),
        ),
    ]
