# Generated by Django 2.2.5 on 2019-10-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191013_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='mythmaker',
            name='profile_image',
            field=models.ImageField(default='No image selected', upload_to='uploads'),
        ),
    ]
