# Generated by Django 2.2.5 on 2019-10-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_mythmaker_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mythmaker',
            name='profile_image',
            field=models.ImageField(default='No image selected', upload_to='profile_images'),
        ),
    ]
