# Generated by Django 2.2.5 on 2019-10-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191015_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='mythmaker',
            name='profile_header',
            field=models.ImageField(default='No image selected', upload_to='profile_headers'),
        ),
    ]
