# Generated by Django 2.2.5 on 2019-10-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_mythmaker_profile_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mythmaker',
            name='profile_image',
            field=models.ImageField(default='profile_images/default-profile.png', upload_to='profile_images'),
        ),
    ]
