# Generated by Django 2.2.5 on 2019-10-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20191016_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mythmaker',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
