# Generated by Django 2.2.5 on 2019-10-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191017_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mythmaker',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='mythmaker',
            name='location',
        ),
    ]
