# Generated by Django 2.2.5 on 2019-10-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        ('accounts', '0018_auto_20191025_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='mythmaker',
            name='uploaded_videos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
