# Generated by Django 2.2.5 on 2019-10-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_mythmaker_uploaded_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mythmaker',
            name='uploaded_videos',
        ),
    ]
