# Generated by Django 2.2.5 on 2019-10-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
