# Generated by Django 2.2.5 on 2019-10-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20191026_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='Recommended image size 1920x1080px', upload_to='thumbnails'),
        ),
    ]
