# Generated by Django 2.2.5 on 2019-11-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20191027_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_likes',
            field=models.IntegerField(default=0),
        ),
    ]
