# Generated by Django 2.2.5 on 2019-11-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_video_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
