# Generated by Django 2.2.5 on 2019-11-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20191112_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
